### ISSUE TITLE
some error in device

### ISSUE THREAD

**Issue by huidemie** [roccotrip/wsd_games_emb#1]
hello,when I run vector_factory.py， using two GPUs. This error :
do you have any ideas?Thank you!
`Traceback (most recent call last):
  File "vector_factory.py", line 79, in <module>
    M.get_word_vectors()
  File "vector_factory.py", line 38, in get_word_vectors
    get_bert_vectors(words, ds, fileid, word_embedding, self.use_svd,self.save_matrices)
  File "/home/li/WSD/wsd_games_emb-master/word_vectors.py", line 250, in get_bert_vectors
    Mat = get_bert(Tokens, Indices, mdl, layer)
  File "/home/li/WSD/wsd_games_emb-master/word_vectors.py", line 105, in get_bert
    all_hidden_states, all_attentions = model(input_ids.cuda(), token_type_ids=None, attention_mask=input_mask.cuda())[-2:]
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 707, in forward
    embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 251, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
`

**Comment by huidemie** [comment]
> hello,when I run vector_factory.py， using two GPUs. This error :
> do you have any ideas?Thank you!
> `Traceback (most recent call last): File "vector_factory.py", line 79, in <module> M.get_word_vectors() File "vector_factory.py", line 38, in get_word_vectors get_bert_vectors(words, ds, fileid, word_embedding, self.use_svd,self.save_matrices) File "/home/li/WSD/wsd_games_emb-master/word_vectors.py", line 250, in get_bert_vectors Mat = get_bert(Tokens, Indices, mdl, layer) File "/home/li/WSD/wsd_games_emb-master/word_vectors.py", line 105, in get_bert all_hidden_states, all_attentions = model(input_ids.cuda(), token_type_ids=None, attention_mask=input_mask.cuda())[-2:] File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__ result = self.forward(*input, **kwargs) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 707, in forward embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__ result = self.forward(*input, **kwargs) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 251, in forward words_embeddings = self.word_embeddings(input_ids) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__ result = self.forward(*input, **kwargs) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward self.norm_type, self.scale_grad_by_freq, self.sparse) File "/home/li/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select `

OK

**Comment by huidemie** [comment]
ok, I solved it. add "model = model.cuda()" before line 105 in wordvector.py
